kategorias:
  - animales
  - bevidas
  - famiya
  - frutas
  - komidas
  - mobles
  - gramer
  - lashon
  - numeros
  - paises
  - plantas
  - profesion
  - ropa
origenes:
  - Jeneral
  - Estanbol
  - Izmir
  - Salonik
  - Balkanes
  - Aki Yerushalayim
  - Torah-Tanah
  - Otros
  - Gresia
  - Ladinokomunita
  - Sarayevo
  - NA
gramatika:
  - adjective
  - adverb
  - noun
  - verb
  - preposition
  - pronoun
  - null
gender:
  - feminine
  - masculine
  - both
  - NA
numero:
  - singular
  - plural
pajinas:
  biervos-de-la-gramer.md: gramer.html
  dias-de-la-semana.md:    dias-de-la-semana.html
  pronombres.md:           pronombres.html
  mezes.md:                mezes.html
  numeros.md:              numeros.html
  ser.md:                  ser.html
  estar.md:                estar.html
  sezones.md:              sezones.html
  puerpo.md:               puerpo.html
  sivdades.md:             sivdades.html
  idiomas.md:              idiomas.html
  nombres.md:              nombres.html
