kategorias:
  - animales
  - bevidas
  - sivdades
  - diminutivos
  - direksion
  - famiya
  - flores
  - frutas
  - insektos
  - komidas
  - mamiferos
  - mobles
  - muzika
  - gramer
  - kolores
  - linguas
  - numeros
  - paises
  - plantas
  - profesion
  - puerpo
  - ropa
  - sports
  - veikolos
  - zarzavates
origenes:
  - Jeneral
  - Estanbol
  - Izmir
  - Ladinadores
  - Salonik
  - Balkanes
  - Aki Yerushalayim
  - Torah-Tanah
  - Otros
  - Gresia
  - Ladinokomunita
  - Sarayevo
  - NA
gramatika:
  - adjective
  - adverb
  - noun
  - verb
  - preposition
  - pronoun
  - null
gender:
  - feminine
  - masculine
  - both
  - NA
numero:
  - singular
  - plural
pajinas:
  biervos-de-la-gramer.md: gramer.html
  pronombres.md:           pronombres.html
  numeros.md:              numeros.html
  ser.md:                  ser.html
  estar.md:                estar.html
  sivdades.md:             sivdades.html
  nombres.md:              nombres.html
listas:
  sezones:
    - primavera
    - enverano
    - otonyo
    - invyerno
  mezes:
    - enero
    - fevrero
    - marso
    - avril
    - mayo
    - junio
    - djulio
    - agosto
    - septembre
    - oktobre
    - novembre
    - decembre
  dias-de-la-semana:
    - alhad
    - lunes
    - martes
    - mierkoles
    - djueves
    - viernes
    - shabat
  kontrarios:
    - grande
    - chiko
    - flako
    - godro
    - alto
    - basho
    - alegre
    - triste
    - vazio
    - yeno
    - mansevo
    - viejo
    - mansevo
    - aedado
    - largo
    - kurto
    - ermozo
    - feo
    - muevo
    - viejo
    - bueno
    - negro
    - prove
    - riko
    - suzio
    - limpio
    - frio
    - kayente
    - fasil
    - difisil
    - kolay
    - zor
    - duro
    - blando
    - liviano
    - pezgado
  enverano:
    - sol
    - plaj
    - banyo de sol
    - banyo de mar
    - parasol
    - shezlong
    - sudor
    - umidita
    - atabafarse de la kalor
    - antojos de sol
    - krema de sol
    - vakansas
    - kaza de kampanya
    - dondurma
    - yalada
    - piknik
    - fuego de shara
    - erkondishen
    - ayre kondisionado
    - pisina
    - havuz
  invierno:
    - luvia
    - pedrisko
    - inyeve
    - bruma
    - relampago
    - rayo
    - entezarse del frio
    - supa
    - chadir
    - guantes
  tiempos:
    - agora
    - amanyana
    - antiyer
    - anoche
    - anyo
    - ayer
    - dekada
    - dia
    - manyana
    - mediodia
    - medianoche
    - mez
    - midi
    - minuto
    - noche
    - ora
    - oy
    - punto
    - segundo
    - semana
    - siglo
    - tadre
    - tadres

tiempos:
  - present indicative
  - pasado simple
  - imperfekto
  - futuro
  - subjunktivo
  - subjunktivo imperfekto
pronombres:
  - yo
  - tu
  - el
  - mozotros
  - vozotros
  - eyos

