kategorias:
  - animales
  - lavoro
origenes:
  - Jeneral
  - Estanbol
  - Izmir
  - Salonik
  - Balkanes
  - Aki Yerushalayim
  - Torah/Tanah
  - Otros
  - Gresia
  - Ladinokomunita
  - Sarayevo
  - NA
gramatika:
  - adjective
  - adverb
  - noun
  - verb
  - preposition
  - pronoun
  - null
gender:
  - feminine
  - masculine
numero:
  - singular
  - plural
