kategorias:
  - animales
  - bevidas
  - famiya
  - frutas
  - komidas
  - mobles
  - muzika
  - gramer
  - lashon
  - numeros
  - paises
  - plantas
  - profesion
  - puerpo
  - ropa
  - veikolos
origenes:
  - Jeneral
  - Estanbol
  - Izmir
  - Salonik
  - Balkanes
  - Aki Yerushalayim
  - Torah-Tanah
  - Otros
  - Gresia
  - Ladinokomunita
  - Sarayevo
  - NA
gramatika:
  - adjective
  - adverb
  - noun
  - verb
  - preposition
  - pronoun
  - null
gender:
  - feminine
  - masculine
  - both
  - NA
numero:
  - singular
  - plural
pajinas:
  biervos-de-la-gramer.md: gramer.html
  pronombres.md:           pronombres.html
  numeros.md:              numeros.html
  ser.md:                  ser.html
  estar.md:                estar.html
  sivdades.md:             sivdades.html
  idiomas.md:              idiomas.html
  nombres.md:              nombres.html
listas:
  sezones:
    - primavera
    - enverano
    - otonyo
    - invyerno
  mezes:
    - enero
    - fevrero
    - marso
    - avril
    - mayo
    - junio
    - djulio
    - agosto
    - septembre
    - oktobre
    - novembre
    - decembre
  dias-de-la-semana:
    - alhad
    - lunes
    - martes
    - mierkoles
    - djueves
    - viernes
    - shabat

