kategorias:
  - animales
  - lavoro
origenes:
  - Jeneral
  - Estanbol
  - Izmir
  - Salonik
  - Balkanes
  - Aki Yerushalayim
  - Torah/Tanah
  - Otros
  - Gresia
  - Ladinokomunita
  - Sarayevo
  - NA
