grammar: verb
orijen: Jeneral

versions:
  - ladino: produzir

    translations:
        english: produce
        french: ''
        portuguese: ''
        spanish: producir
        turkish: üretmek

conjugations: {}


