examples: []
grammar: null
id: '2108'
origen: Jeneral
versions:
-   accented: produzir
    ladino: produzir
    translations:
        english: produce
        french: ''
        portuguese: ''
        spanish: producir
        turkish: üretmek
