grammar: NA
id: '2107'
orijen: Jeneral

versions:
  - ladino: produizirse

    translations:
        english:
        - take place
        - happen
        french: ''
        portuguese: ''
        spanish: producirse
        turkish: meydana gelmek


