grammar: null
id: '903'
origen: Jeneral

versions:
  - ladino: prodjekto

    gender: masculine
    number: singular

    translations:
        english: project
        french: ''
        portuguese: ''
        spanish: proyecto
        turkish: proje

examples: []
