grammar: NA
id: '903'
orijen: Jeneral

versions:
  - ladino: prodjekto

    alternative-spelling:
      - ladino: proyekto

    gender: masculine
    number: singular

    translations:
        english: project
        french: ''
        portuguese: ''
        spanish: proyecto
        turkish: proje


