grammar: noun
orijen: Ladinokomunita

versions:
  - ladino: produkto

    gender: masculine
    number: singular

    translations:
      english: product
      french: ''
      hebrew: ''
      portuguese: ''
      spanish: producto
      turkish: ''

  - ladino: produktos

    gender: masculine
    number: plural

    translations:
      english: products
      french: ''
      hebrew: ''
      portuguese: ''
      spanish: productos
      turkish: ''


