grammar: noun
orijen: Ladinokomunita

versions:
  - ladino: produkto

    gender: masculine
    number: singular

    translations:
      inglez: product
      fransez: ''
      ebreo: ''
      portugez: ''
      kasteyano: producto
      turko: ''

  - ladino: produktos

    gender: masculine
    number: plural

    translations:
      inglez: products
      fransez: ''
      ebreo: ''
      portugez: ''
      kasteyano: productos
      turko: ''


