grammar: verb
id: '2108'
origen: Jeneral

versions:
  - ladino: produzir

    translations:
        english: produce
        french: ''
        portuguese: ''
        spanish: producir
        turkish: üretmek

conjugations: {}


