grammar: NA
orijen: Jeneral

versions:
  - ladino: prodjekto

    alternative-spelling:
      - ladino: proyekto

    gender: masculine
    number: singular

    translations:
        inglez: project
        fransez: ''
        portugez: ''
        kasteyano: proyecto
        turko: proje


