grammar: verb
orijen: Jeneral

versions:
  - ladino: produzir

    translations:
        inglez: produce
        fransez: ''
        portugez: ''
        kasteyano: producir
        turko: üretmek

conjugations: {}


