grammar: NA
orijen: Jeneral

versions:
  - ladino: produizirse

    translations:
        inglez:
        - take place
        - happen
        fransez: ''
        portugez: ''
        kasteyano: producirse
        turko: meydana gelmek


