grammar: verb
id: '2132'
orijen: Jeneral

versions:
  - ladino: render

    translations:
        english: yield
        french: ''
        portuguese: ''
        spanish: rendir
        turkish: vermek (ürün)

conjugations: {}


